- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/ProjectController.java
- src/main/java/com/matching/project/dto/Response.java
- src/main/java/com/matching/project/dto/ResponseDto.java
- src/main/java/com/matching/project/dto/project/ProjectPositionDto.java
- src/main/java/com/matching/project/dto/project/ProjectRegisterRequestDto.java
- src/main/java/com/matching/project/dto/project/ProjectRegisterResponseDto.java
- src/main/java/com/matching/project/entity/Project.java
- src/main/java/com/matching/project/entity/ProjectPosition.java
- src/main/java/com/matching/project/entity/ProjectTechnicalStack.java
- src/main/java/com/matching/project/service/ProjectService.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/main/resources/application.yml
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
- src/test/java/com/matching/project/service/ProjectServiceImplTest.java
- src/test/resources/application.yml
> feat: Add Project register func

- src/main/java/com/matching/project/entity/ProjectUser.java
- src/main/java/com/matching/project/repository/ProjectUserRepository.java
- src/main/java/com/matching/project/service/ProjectService.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/test/java/com/matching/project/service/ProjectServiceImplTest.java
projectUser 등록 미구현으로 인한 기존 projectRegister 메소드 수정
> update: Update projectUser add

- src/main/java/com/matching/project/controller/ProjectController.java
- src/main/java/com/matching/project/dto/project/ProjectSimpleDto.java
- src/main/java/com/matching/project/entity/BookMark.java
- src/main/java/com/matching/project/entity/Image.java
- src/main/java/com/matching/project/entity/Project.java
- src/main/java/com/matching/project/entity/ProjectUser.java
- src/main/java/com/matching/project/entity/User.java
- src/main/java/com/matching/project/repository/BookMarkRepository.java
- src/main/java/com/matching/project/repository/ProjectRepository.java
- src/main/java/com/matching/project/repository/ProjectUserRepository.java
- src/main/java/com/matching/project/service/ProjectService.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
- src/test/java/com/matching/project/repository/BookMarkRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectRepositoryTest.java
- src/test/java/com/matching/project/service/ProjectServiceImplTest.java
- src/test/resources/application.yml
현재 모집 중인 프로젝트 리스트 조회 기능 구현 완료했습니다.
1. 아직 JWT 기능 미구현으로 인해 하드 코딩으로 유저 번호를 넣어 놓은 상태입니다. JWT 기능 구현 완료시 수정할 예정입니다.
SecurityContextHolder를 통해 유저 번호를 가져오는 방식으로 수정할 예정입니다.
2. 이미지 업로드, 다운로드 기능이 구현되지 않아 profile, image 부분은 null로 처리해 놓았습니다. 
추후 이미지 업로드, 다운로드 기능이 구현되면 수정할 예정입니다.
> feat: Add ProjectRecruitingList func

- build.gradle
- src/main/java/com/matching/project/config/JwtAuthenticationFilter.java
- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/CommonController.java
- src/main/java/com/matching/project/controller/UserController.java
- src/main/java/com/matching/project/dto/user/EmailAuthRequestDto.java
- src/main/java/com/matching/project/dto/user/SignUpRequestDto.java
- src/main/java/com/matching/project/entity/EmailAuth.java
- src/main/java/com/matching/project/entity/User.java
- src/main/java/com/matching/project/oauth/OAathSuccessHandler.java
- src/main/java/com/matching/project/oauth/OAuthAttributes.java
- src/main/java/com/matching/project/repository/EmailAuthRepository.java
- src/main/java/com/matching/project/service/CommonService.java
- src/main/java/com/matching/project/service/CommonServiceImpl.java
- src/main/java/com/matching/project/service/CustomUserDetailsService.java
- src/main/java/com/matching/project/service/EmailService.java
- src/main/java/com/matching/project/service/EmailServiceImpl.java
- src/main/java/com/matching/project/service/JwtTokenService.java
- src/main/java/com/matching/project/service/UserServiceImpl.java
- src/main/resources/application-local.yml
- src/test/java/com/matching/project/service/CommonServiceImplTest.java
- src/test/java/com/matching/project/service/EmailServiceImplTest.java
- src/test/java/com/matching/project/service/JwtTokenServiceTest.java
- src/test/java/com/matching/project/service/UserServiceTest.java
추가 작업 내역
1. Jwt 인증 부분 {no} 제거
2. Login 및 SignUp 리펙토링
3. 리펙토링으로 인한 각 테스트 케이스 수정
> feat: Add email authentication at login

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/dto/project/ProjectRegisterResponseDto.java
- src/main/java/com/matching/project/entity/Project.java
- src/main/java/com/matching/project/entity/User.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
JWT 추가로 인한 프로젝트 등록 기능 업데이트입니다.
> update: Update project register func

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/CommonController.java
- src/main/java/com/matching/project/controller/UserController.java
- src/main/java/com/matching/project/dto/common/PasswordReissueCallRequestDto.java
- src/main/java/com/matching/project/dto/common/PasswordReissueResponseDto.java
- src/main/java/com/matching/project/dto/enumerate/EmailAuthPurpose.java
- src/main/java/com/matching/project/dto/user/EmailAuthReSendRequestDto.java
- src/main/java/com/matching/project/dto/user/EmailAuthRequestDto.java
- src/main/java/com/matching/project/entity/EmailAuth.java
- src/main/java/com/matching/project/entity/User.java
- src/main/java/com/matching/project/repository/EmailAuthRepository.java
- src/main/java/com/matching/project/service/EmailService.java
- src/main/java/com/matching/project/service/EmailServiceImpl.java
- src/test/java/com/matching/project/service/EmailServiceImplTest.java
패스워드 재발급 기능 추가 하였습니다. 
단, OAtuh2.0으로 로그인하는 유저는 패스워드 재발급이 불가능하게 처리하였습니다.
추가 작업 내역
1. 로그아웃 추가 (jwt 토큰 제거는 프론트 쪽에서 해줘야함)
2. EmailService 내 중복되는 작업이 많아 리펙토링 실시
> feat: Add password reissue func

- src/main/java/com/matching/project/dto/project/ProjectDto.java
- src/main/java/com/matching/project/dto/project/ProjectPositionDetailDto.java
- src/main/java/com/matching/project/repository/BookMarkRepository.java
- src/main/java/com/matching/project/repository/CommentRepository.java
- src/main/java/com/matching/project/repository/ProjectPositionRepository.java
- src/main/java/com/matching/project/repository/ProjectRepository.java
- src/main/java/com/matching/project/repository/ProjectTechnicalStackRepository.java
- src/main/java/com/matching/project/repository/TechnicalStackRepository.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
- src/test/java/com/matching/project/repository/BookMarkRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectPositionRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectTechnicalStackRepositoryTest.java
- src/test/java/com/matching/project/service/ProjectServiceImplTest.java
ERD 변경으로 인한 프로젝트 상세 조회 기능을 수정했습니다.
추후에 이미지 기능이 추가되면 수정이 필요합니다.
> update: Update projectInfo func

- build.gradle
- src/main/java/com/matching/project/config/QuerydslConfiguration.java
- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/ProjectController.java
- src/main/java/com/matching/project/dto/enumerate/Filter.java
- src/main/java/com/matching/project/dto/enumerate/ProjectSearchFilter.java
- src/main/java/com/matching/project/dto/project/ProjectSearchDto.java
- src/main/java/com/matching/project/dto/project/ProjectSimpleDto.java
- src/main/java/com/matching/project/dto/project/ProjectSimplePositionDto.java
- src/main/java/com/matching/project/dto/project/ProjectSimpleTechnicalStackDto.java
- src/main/java/com/matching/project/entity/Project.java
- src/main/java/com/matching/project/repository/ProjectRepository.java
- src/main/java/com/matching/project/repository/ProjectRepositoryCustom.java
- src/main/java/com/matching/project/repository/ProjectRepositoryImpl.java
- src/main/java/com/matching/project/service/ProjectService.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
- src/test/java/com/matching/project/repository/BookMarkRepositoryTest.java
- src/test/java/com/matching/project/repository/CommentRepositoryTest.java
- src/test/java/com/matching/project/repository/PositionRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectPositionRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectTechnicalStackRepositoryTest.java
- src/test/java/com/matching/project/repository/TechnicalStackRepositoryTest.java
- src/test/java/com/matching/project/service/ProjectServiceImplTest.java
기존에 있던 프로젝트 목록 조회 기능을 프로젝트 검색 기능으로 통합하였습니다.
추후에 이미지 기능이 생기면 수정이 필요합니다.
> add: Add projectSearch func

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/TechnicalStackController.java
- src/main/java/com/matching/project/dto/technicalstack/TechnicalStackUpdateRequestDto.java
- src/main/java/com/matching/project/entity/TechnicalStack.java
- src/main/java/com/matching/project/repository/ImageRepository.java
- src/main/java/com/matching/project/repository/TechnicalStackRepository.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/main/java/com/matching/project/service/TechnicalStackService.java
- src/main/java/com/matching/project/service/TechnicalStackServiceImpl.java
- src/test/java/com/matching/project/controller/TechnicalStackControllerTest.java
- src/test/java/com/matching/project/repository/ImageRepositoryTest.java
- src/test/java/com/matching/project/service/TechnicalStackServiceImplTest.java
기술스택 추가 폼, 기술스택 추가, 기술스택 수정 기능 완료했습니다.
기술스택 추가 및, 수정 기능은 추후 통합테스트가 필요합니다.
> add: Add technical_stack_crud

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/ProjectController.java
- src/main/java/com/matching/project/controller/ProjectParticipateController.java
- src/main/java/com/matching/project/dto/project/ProjectUpdateRequestDto.java
- src/main/java/com/matching/project/dto/projectposition/ProjectPositionAddDto.java
- src/main/java/com/matching/project/entity/Project.java
- src/main/java/com/matching/project/entity/ProjectPosition.java
- src/main/java/com/matching/project/repository/ProjectPositionRepository.java
- src/main/java/com/matching/project/repository/ProjectRepositoryCustom.java
- src/main/java/com/matching/project/repository/ProjectRepositoryImpl.java
- src/main/java/com/matching/project/repository/ProjectTechnicalStackRepository.java
- src/main/java/com/matching/project/repository/TechnicalStackRepository.java
- src/main/java/com/matching/project/service/ProjectService.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
- src/test/java/com/matching/project/repository/ProjectPositionRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectTechnicalStackRepositoryTest.java
- src/test/java/com/matching/project/service/ProjectServiceImplTest.java
> add: Add projectUpdate func

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/ProjectController.java
- src/main/java/com/matching/project/entity/Project.java
- src/main/java/com/matching/project/entity/ProjectParticipateRequest.java
- src/main/java/com/matching/project/repository/BookMarkRepository.java
- src/main/java/com/matching/project/repository/CommentRepository.java
- src/main/java/com/matching/project/repository/ParticipateRequestTechnicalStackRepository.java
- src/main/java/com/matching/project/repository/ParticipateRequestTechnicalStackRepositoryCustom.java
- src/main/java/com/matching/project/repository/ParticipateRequestTechnicalStackRepositoryImpl.java
- src/main/java/com/matching/project/repository/ProjectParticipateRequestRepository.java
- src/main/java/com/matching/project/repository/ProjectParticipateRequestRepositoryCustom.java
- src/main/java/com/matching/project/repository/ProjectParticipateRequestRepositoryImpl.java
- src/main/java/com/matching/project/repository/ProjectPositionRepository.java
- src/main/java/com/matching/project/repository/ProjectRepositoryImpl.java
- src/main/java/com/matching/project/service/BookMarkServiceImpl.java
- src/main/java/com/matching/project/service/ProjectService.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
- src/test/java/com/matching/project/repository/BookMarkRepositoryTest.java
- src/test/java/com/matching/project/repository/CommentRepositoryTest.java
- src/test/java/com/matching/project/repository/ParticipateRequestTechnicalStackRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectParticipateRequestRepositoryTest.java
- src/test/java/com/matching/project/repository/ProjectPositionRepositoryTest.java
- src/test/java/com/matching/project/service/BookMarkServiceImplTest.java
- src/test/java/com/matching/project/service/ProjectServiceImplTest.java
> add: Add projectDelete func

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/controller/ProjectPositionController.java
- src/main/java/com/matching/project/error/ErrorCode.java
- src/main/java/com/matching/project/repository/ProjectPositionRepository.java
- src/main/java/com/matching/project/service/ProjectPositionService.java
- src/main/java/com/matching/project/service/ProjectPositionServiceImpl.java
- src/test/java/com/matching/project/controller/ProjectPositionControllerTest.java
- src/test/java/com/matching/project/repository/ProjectPositionRepositoryTest.java
- src/test/java/com/matching/project/service/ProjectPositionServiceImplTest.java
> add: Add projectPosition withdraw and expulsion func

- src/main/java/com/matching/project/repository/UserRepository.java
- src/main/java/com/matching/project/service/CommentServiceImpl.java
- src/main/java/com/matching/project/service/NotificationServiceImpl.java
- src/main/java/com/matching/project/service/PositionServiceImpl.java
- src/main/java/com/matching/project/service/UserServiceImpl.java
- src/main/resources/application-local.yml
- src/test/java/com/matching/project/controller/UserControllerTest.java
- src/test/java/com/matching/project/repository/UserRepositoryTest.java
- src/test/java/com/matching/project/service/CommentServiceImplTest.java
- src/test/java/com/matching/project/service/NotificationServiceImplTest.java
- src/test/java/com/matching/project/service/UserServiceTest.java
- src/test/resources/application.yml
SecurityContextHolder 에서 받아오는 객체는 영속상태가 아니여서 업데이트가 반영이 안될 뿐더러, 연관관계에 있는 객체 또한 가져오지 못하여 해당 이슈가 발생했습니다. 따라서 한번 더 조회하도록 코드를 일시적으로 수정하였습니다.
- #67
> !HOTFIX: Fix #67 issue

- src/main/java/com/matching/project/service/ProjectServiceImpl.java
기존에 ProjectRegisterUserDto의 no에 null이 들어가도 유저가 들어가는 문제 해결
- #57
> update: update ProjectServiceImpl projectRegister func

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/test/java/com/matching/project/controller/TechnicalStackControllerTest.java
GET /v1/technicalStack 권한을 기존의 어드민에서 (유저, 어드민)으로 변경했습니다.
- #79 
- @Olivia-SY129 @younchong
> feat: feat GET /v1/technicalStack Authorization User

- src/main/java/com/matching/project/controller/TechnicalStackController.java
- src/test/java/com/matching/project/controller/TechnicalStackControllerTest.java
기존 기술스택 수정 실패했을때 테스트 추가했습니다.
- #39
> feat: feat TechnicalStackControllerTest technicalStackUpdate

- src/main/java/com/matching/project/config/SecurityConfig.java
권한을 계층 구조로 바꿔서 ADMIN일 경우 ADMIN, USER, ANONYMOUSE 접근 가능, USER일 경우 USER, ANONYMOUSE 접근 가능, ANONYMOUSE일 경우 ANONYMOUSE 접근 가능으로 변경했습니다.
> feat: feat RoleHierarchy

- src/main/resources/logback.xml
> feat: feat logback setting

- src/main/java/com/matching/project/repository/ProjectRepositoryImpl.java
- src/test/java/com/matching/project/repository/ProjectRepositoryTest.java
프로젝트 리스트 조회시 모집중인 포지션만 반환하게 변경했습니다.
- #87 
@Olivia-SY129
> update: update ProjectRepositoryImpl findProjectPositionMap func

- src/main/java/com/matching/project/config/SecurityConfig.java
> feat: Add cors configuration

- src/main/java/com/matching/project/dto/user/ProjectRegisterUserDto.java
- src/main/java/com/matching/project/service/ProjectServiceImpl.java
기존에 ProjectRegisterUserDto no를 userNo로 바꿨습니다.
- #94
> update: update ProjectRegisterUserDto userNo

- build.gradle
- src/main/java/com/matching/project/config/EmbeddedRedisConfig.java
- src/main/java/com/matching/project/entity/Project.java
- src/main/java/com/matching/project/service/UserServiceImpl.java
- src/main/resources/application-local.yml
- src/test/java/com/matching/project/config/EmbeddedRedisConfig.java
- src/test/java/com/matching/project/config/EmbeddedRedisConfigTest.java
- src/test/resources/application.yml
로컬 및 테스트 환경에서 Embedded Redis 사용할 수 있도록 작성.
추가로 수정된 이슈는 아래와 같습니다.
- #93
Closes #91, Closes #93
> feat: Add Embedded Redis

- src/main/java/com/matching/project/service/JwtTokenService.java
- src/test/java/com/matching/project/config/EmbeddedRedisConfig.java
- src/test/java/com/matching/project/config/EmbeddedRedisConfigTest.java
- src/test/java/com/matching/project/controller/BookMarkControllerTest.java
- src/test/java/com/matching/project/controller/CommentControllerTest.java
- src/test/java/com/matching/project/controller/CommonControllerTest.java
- src/test/java/com/matching/project/controller/NotificationControllerTest.java
- src/test/java/com/matching/project/controller/PositionControllerTest.java
- src/test/java/com/matching/project/controller/ProjectControllerTest.java
- src/test/java/com/matching/project/controller/ProjectParticipateControllerTest.java
- src/test/java/com/matching/project/controller/ProjectPositionControllerTest.java
- src/test/java/com/matching/project/controller/TechnicalStackControllerTest.java
- src/test/java/com/matching/project/controller/UserControllerTest.java
기존 임베디드 레디스 연결 문제 해결 및, jwt UUID 추가했습니다.
> update: update EmbeddedRedisConfig

- src/main/java/com/matching/project/dto/notification/NotificationDto.java
- src/main/java/com/matching/project/service/NotificationServiceImpl.java
- src/test/java/com/matching/project/controller/NotificationControllerTest.java
- src/test/java/com/matching/project/service/NotificationServiceImplTest.java
아직 type 값이 리스폰 되는 항목이 있어서 마저 수정하였습니다.
> fix: Fix Notification Issue #103

- Dockerfile
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/main/resources/logback/logback.xml
운영서버용 yml 파일 생성 및, 기존 Dockerfile -Dspring.profiles.active=prod로 변경
> feat: feat application-prod.yml

- src/main/java/com/matching/project/config/EmbeddedRedisConfig.java
- src/main/java/com/matching/project/dto/user/UserFilterDto.java
- src/main/java/com/matching/project/dto/user/UserSimpleInfoDto.java
- src/main/java/com/matching/project/repository/UserRepositoryImpl.java
- src/main/java/com/matching/project/service/UserServiceImpl.java
- src/test/java/com/matching/project/controller/UserControllerTest.java
- src/test/java/com/matching/project/service/UserServiceTest.java
아래 이슈도 추가로 수정
- #110 : filter 및 content가 입력되지 않았을 경우 처리 추가
> feat: Add blocked user data in userInfoList(#111)

- src/main/java/com/matching/project/config/SecurityConfig.java
- src/main/java/com/matching/project/entity/User.java
- src/main/java/com/matching/project/service/UserServiceImpl.java
아래 이슈들 처리완료하였습니다.
- #121 : 유저에게 포지션 번호가 할당되고 로그인을 시도 했을때 나던 에러 수정
- #120 : 토큰 만료 이전에 재발급을 시도해도 해당 API에 접근할 수 있도록 수정
- #119 : 회원 목록 조회시 관리자 계정을 보이지 않도록 수정
> HOTFIX! : Hotfix issue resolution
